name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: 103.175.219.185
          username: sayuran
          key: b3B1bnNzaC1r2XktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABIWAAAAdzc2gten NhâAAAAEAAQAAAYERvtphauCIto5kVNd jPFEOX jUQXGCPnHpx+EL82DuDQ5Pvs9YGqbJg| DaBAVh1YqCENOj+BuuMDKKRy58XLI/sko9U7VraW5Md+wGRf3g7Y5Hz+nhUAZJFo/FFEOG EVKTADnJ5T+5y2++y07tWX2noQy+2rgdcLs82QuYf6DhvzIQpdoYgCVZ3bROX1FtduP51S KOF2bfqj30Ryosr JL71UdhN00SzzU77SnFhjq6VнbJfpHF 1AJO 1oYfESYLPUKS4VF207fN AEh3YPBhV3dXXIXXUP+1TJFTSB7jNi+za7SWnEPF IH6poRгS0hPo051g7yV99dWTz2pNdC DKWALKBJEOUPWXVIypgJxuH9oy408HzPab9VSy2B62WeJuo5UaYh/UpzoйtrZcVBJBWnqu duu8djW1YOVGP/n6Rhc67141GhVrd1M0tQ0DH6ekonEYc57VEyUUd/svoQXNdYVu8BZF18 gS6B4fKuEhAuaddHbKcAu18z2+3N7MPvfomnwqnPAAAFKFxokbtcaCm7AAAAB3NzaC1yc2 EAAAGBAL 7aVmrgiLX0ZFTXYZXRNMY1EMRgJ5x6cfhC/Ng8A00T77PWBqmy YDmgQFYdWKgh DTo/gbr jAypEcufMSyP7JKPV01a2luTHf SBKX94020R8/p4VAGSRAPXRRKBhLyrQA5yeU/ uctvvsju7V19p6EMvtq4HXC7PNkLmH+g4b8yEKXaGIA1Wd20T15Rbxbj+ZUpNBdm36099E CqLKYS+5VHYTTtES810+0pxYY6u1R2yX6RxZQCdIqGHXOWCZ1CkuFRdq03ZQBId2DwYVd3 V1yMV1D/ok4xU7Ae4zYvs2u01pxDxSB+qaEa0joT6DuSI081ffXVk89qTXQg5MACSAYXD1 D8F1SMqYCcbh/aMuKPB8z2m/VUstget Inibq0VGmIf 1Kc6ALa2XFQYwVp61HVLVHY1TWNF Rj/5+kYXOu7eJRoVa3d TDгUDgx+niqJxGH0e1RM1FHf7L6EFZXWFbVACXYVIEugeHyrhIQ LmnXR2ynALpfM2ftzezD736Jp8KpzwAAAAMBAAEAAAGAAZALHTLBWC3B0nгgp2VSQIEZVC 9TWtoTf+d3X2+Ycy5/k7eaQJAGAZ715GL6eWa0PC55VdvD55B0U8MaJRXA7SDNPthVzM/2 Xukni17J2SIYVCT079Jef+/T/d4aHnC1T6TBKXb5CXWChZjDabq05122rR8ndt0Q1qcf9f Xqk9ACHeQu3mC/SVWh2010y5MjkbubqhA/q6gjotvJ0Q3W/4uR3kMkPnvmb5tkj9mJbNM2 7Shq6Qbw62J/uEUV4HCPKRp1PQ2zjdQSh61U4bNfv1dXT6RUdGSiykKXIVNCpTd6YeGb3T h19eDxD9+/13vhKGTazw+d02KMHuel+AAVOWJNAQAIKxGzc2gnGTFruFjQEMf5/pkd17uk hY5VSYLBSKStrYoEbsrA80Png7SzoiboGHC1tY1K072doCtUMYA3ae+rc0nk in Juk 7x6uF 8DJHMZRNIhvFhdQFHZgGzDexn7sMhu/gX6rs9Fn/GWHOK+HAobFAvaBX9xce5DMpn5AAAA QCqGNdUSieUkcH9JRq5GnnZk5Zrd7WAckicCGrZBP IHwPnVNAbKZ1LZu01yoiqta7Dtx1 1q08zpSiPWvYX9dhRtdbnVuZpIgoBaoW2195VRT/qSZXb+ciC600hR+4zosRv0wmJmVxH2 DoB601h6 TQTU8yr MVZjJWYNc8FeB6tYQeMq7ISRJIviD101a4913GqmRXiTEVTEUMbuCZB 4201609fL2HS2KXE/R24fpQIBJ+G1bUZSoDhvNnjD1VT8w4u0AAADBA0CCU3WSRYAFMAT1 iVhqjSC JNTUT+/39fw9CR1000/kVbv1J8wzmWVX5uk1bRxBFe20Sf Io 18Gdt0xMW9SZISC L3gnCOPgVM4pUDABZm/LHtNRYhA6/NW6YOdUY9xvXEVIBgJxEdAQ2cjr40K+Vd0Y/JKbNg aL 1hPAе5gPBFIGMbWSгWu7BIFutZ2UYr0gsVHM6Gaz9MWvhnkmMgOMuhgAW1kpn6CxYYOC TJ7ZTLZk7L TCKPvboRG2upMQE4+7AiowAAAMEA03/01t1070SP1941c1n9LDUnMrOrg6wh tOP+aR+7gjiXNCGt T57q1onjPk+oy+KAy9/UPMYeGFPNTSA5SGUM1bxs4pCimnjCq6neG8 sq+Gyc2JQ1NOUCocJzZzL/St1t13umaJDEufe4f0W+/7mok T9UgsjrBeq8TDBfKR4ugDnv
          script: |
            cd /var/www/html
            git pull origin master
